/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubeovn/kube-ovn/pkg/client/clientset/versioned/typed/kubeovn/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFabricV1 struct {
	*testing.Fake
}

func (c *FakeFabricV1) BgpConves() v1.BgpConfInterface {
	return newFakeBgpConves(c)
}

func (c *FakeFabricV1) DNSNameResolvers() v1.DNSNameResolverInterface {
	return newFakeDNSNameResolvers(c)
}

func (c *FakeFabricV1) IPs() v1.IPInterface {
	return newFakeIPs(c)
}

func (c *FakeFabricV1) IPPools() v1.IPPoolInterface {
	return newFakeIPPools(c)
}

func (c *FakeFabricV1) OvnDnatRules() v1.OvnDnatRuleInterface {
	return newFakeOvnDnatRules(c)
}

func (c *FakeFabricV1) OvnEips() v1.OvnEipInterface {
	return newFakeOvnEips(c)
}

func (c *FakeFabricV1) OvnFips() v1.OvnFipInterface {
	return newFakeOvnFips(c)
}

func (c *FakeFabricV1) OvnSnatRules() v1.OvnSnatRuleInterface {
	return newFakeOvnSnatRules(c)
}

func (c *FakeFabricV1) ProviderNetworks() v1.ProviderNetworkInterface {
	return newFakeProviderNetworks(c)
}

func (c *FakeFabricV1) RouterLBRules() v1.RouterLBRuleInterface {
	return newFakeRouterLBRules(c)
}

func (c *FakeFabricV1) SecurityGroups() v1.SecurityGroupInterface {
	return newFakeSecurityGroups(c)
}

func (c *FakeFabricV1) Subnets() v1.SubnetInterface {
	return newFakeSubnets(c)
}

func (c *FakeFabricV1) SwitchLBRules() v1.SwitchLBRuleInterface {
	return newFakeSwitchLBRules(c)
}

func (c *FakeFabricV1) Vips() v1.VipInterface {
	return newFakeVips(c)
}

func (c *FakeFabricV1) Vlans() v1.VlanInterface {
	return newFakeVlans(c)
}

func (c *FakeFabricV1) Vpcs() v1.VpcInterface {
	return newFakeVpcs(c)
}

func (c *FakeFabricV1) VpcDnses() v1.VpcDnsInterface {
	return newFakeVpcDnses(c)
}

func (c *FakeFabricV1) VpcEgressGateways(namespace string) v1.VpcEgressGatewayInterface {
	return newFakeVpcEgressGateways(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFabricV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
