{
 "title": "fabric / OVS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(process_cpu_seconds_total{job=\"fabric-pinger\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "OVS Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allIsZero" ] } },
   "targets": [
    {
     "expr": "sum(pinger_ovs_down{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "DB Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_ovn_ovs_info{instance=~\"$instance\"}) by (db_version)",
     "legendFormat": "{{db_version}}"
    }
   ]
  },
  {
   "title": "OVS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_ovn_ovs_info{instance=~\"$instance\"}) by (ovs_version)",
     "legendFormat": "{{ovs_version}}"
    }
   ]
  },
  {
   "title": "Datapath Flow Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_ovn_dp_flows_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Flow Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(kube_ovn_dp_flows_lookup_hit{instance=~\"$instance\"}[1m])/(increase(kube_ovn_dp_flows_lookup_hit{instance=~\"$instance\"}[1m])+increase(kube_ovn_dp_flows_lookup_missed{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_ovn_db_file_size_bytes{instance=~\"$instance\", hostname!=\"localhost\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_ovn_log_file_size_bytes{instance=~\"$instance\", hostname!=\"localhost\"}",
     "legendFormat": "{{instance}} {{component}}"
    }
   ]
  },
  {
   "title": "Interface Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_ovn_dp_if_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packets Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_ovn_interface_rx_packets{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} rx"
    },
    {
     "expr": "sum(delta(kube_ovn_interface_tx_packets{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} tx"
    }
   ]
  },
  {
   "title": "Bytes Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_ovn_interface_rx_bytes{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} rx"
    },
    {
     "expr": "sum(delta(kube_ovn_interface_tx_bytes{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} tx"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ovs-ovn.*\", container!=\"POD\"}) by (pod, node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"ovs-ovn.*\", container!=\"POD\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}