/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// LoadBalancerFrontendApplyConfiguration represents a declarative configuration of the LoadBalancerFrontend type for use
// with apply.
type LoadBalancerFrontendApplyConfiguration struct {
	Vip    *string `json:"vip,omitempty"`
	OvnEip *string `json:"ovnEip,omitempty"`
}

// LoadBalancerFrontendApplyConfiguration constructs a declarative configuration of the LoadBalancerFrontend type for use with
// apply.
func LoadBalancerFrontend() *LoadBalancerFrontendApplyConfiguration {
	return &LoadBalancerFrontendApplyConfiguration{}
}

// WithVip sets the Vip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vip field is set to the value of the last call.
func (b *LoadBalancerFrontendApplyConfiguration) WithVip(value string) *LoadBalancerFrontendApplyConfiguration {
	b.Vip = &value
	return b
}

// WithOvnEip sets the OvnEip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OvnEip field is set to the value of the last call.
func (b *LoadBalancerFrontendApplyConfiguration) WithOvnEip(value string) *LoadBalancerFrontendApplyConfiguration {
	b.OvnEip = &value
	return b
}
