/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DnsZoneLister helps list DnsZones.
// All objects returned here must be treated as read-only.
type DnsZoneLister interface {
	// List lists all DnsZones in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.DnsZone, err error)
	// Get retrieves the DnsZone from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.DnsZone, error)
	DnsZoneListerExpansion
}

// dnsZoneLister implements the DnsZoneLister interface.
type dnsZoneLister struct {
	listers.ResourceIndexer[*kubeovnv1.DnsZone]
}

// NewDnsZoneLister returns a new DnsZoneLister.
func NewDnsZoneLister(indexer cache.Indexer) DnsZoneLister {
	return &dnsZoneLister{listers.New[*kubeovnv1.DnsZone](indexer, kubeovnv1.Resource("dnszone"))}
}
