/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/cloudyfolks-labs/fabric/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BgpConves returns a BgpConfInformer.
	BgpConves() BgpConfInformer
	// DNSZones returns a DNSZoneInformer.
	DNSZones() DNSZoneInformer
	// IPs returns a IPInformer.
	IPs() IPInformer
	// IPPools returns a IPPoolInformer.
	IPPools() IPPoolInformer
	// LoadBalancerPools returns a LoadBalancerPoolInformer.
	LoadBalancerPools() LoadBalancerPoolInformer
	// OvnDnatRules returns a OvnDnatRuleInformer.
	OvnDnatRules() OvnDnatRuleInformer
	// OvnEips returns a OvnEipInformer.
	OvnEips() OvnEipInformer
	// OvnFips returns a OvnFipInformer.
	OvnFips() OvnFipInformer
	// OvnSnatRules returns a OvnSnatRuleInformer.
	OvnSnatRules() OvnSnatRuleInformer
	// ProviderNetworks returns a ProviderNetworkInformer.
	ProviderNetworks() ProviderNetworkInformer
	// RouterLBRules returns a RouterLBRuleInformer.
	RouterLBRules() RouterLBRuleInformer
	// SecurityGroups returns a SecurityGroupInformer.
	SecurityGroups() SecurityGroupInformer
	// Subnets returns a SubnetInformer.
	Subnets() SubnetInformer
	// SwitchLBRules returns a SwitchLBRuleInformer.
	SwitchLBRules() SwitchLBRuleInformer
	// Vips returns a VipInformer.
	Vips() VipInformer
	// Vlans returns a VlanInformer.
	Vlans() VlanInformer
	// Vpcs returns a VpcInformer.
	Vpcs() VpcInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BgpConves returns a BgpConfInformer.
func (v *version) BgpConves() BgpConfInformer {
	return &bgpConfInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// DNSZones returns a DNSZoneInformer.
func (v *version) DNSZones() DNSZoneInformer {
	return &dnsZoneInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IPs returns a IPInformer.
func (v *version) IPs() IPInformer {
	return &iPInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IPPools returns a IPPoolInformer.
func (v *version) IPPools() IPPoolInformer {
	return &iPPoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LoadBalancerPools returns a LoadBalancerPoolInformer.
func (v *version) LoadBalancerPools() LoadBalancerPoolInformer {
	return &loadBalancerPoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// OvnDnatRules returns a OvnDnatRuleInformer.
func (v *version) OvnDnatRules() OvnDnatRuleInformer {
	return &ovnDnatRuleInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// OvnEips returns a OvnEipInformer.
func (v *version) OvnEips() OvnEipInformer {
	return &ovnEipInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// OvnFips returns a OvnFipInformer.
func (v *version) OvnFips() OvnFipInformer {
	return &ovnFipInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// OvnSnatRules returns a OvnSnatRuleInformer.
func (v *version) OvnSnatRules() OvnSnatRuleInformer {
	return &ovnSnatRuleInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ProviderNetworks returns a ProviderNetworkInformer.
func (v *version) ProviderNetworks() ProviderNetworkInformer {
	return &providerNetworkInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// RouterLBRules returns a RouterLBRuleInformer.
func (v *version) RouterLBRules() RouterLBRuleInformer {
	return &routerLBRuleInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// SecurityGroups returns a SecurityGroupInformer.
func (v *version) SecurityGroups() SecurityGroupInformer {
	return &securityGroupInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Subnets returns a SubnetInformer.
func (v *version) Subnets() SubnetInformer {
	return &subnetInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// SwitchLBRules returns a SwitchLBRuleInformer.
func (v *version) SwitchLBRules() SwitchLBRuleInformer {
	return &switchLBRuleInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Vips returns a VipInformer.
func (v *version) Vips() VipInformer {
	return &vipInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Vlans returns a VlanInformer.
func (v *version) Vlans() VlanInformer {
	return &vlanInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Vpcs returns a VpcInformer.
func (v *version) Vpcs() VpcInformer {
	return &vpcInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
