/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	fabricv1 "github.com/cloudyfolks-labs/fabric/pkg/apis/fabric/v1"
	applyconfigurationfabricv1 "github.com/cloudyfolks-labs/fabric/pkg/client/applyconfiguration/fabric/v1"
	scheme "github.com/cloudyfolks-labs/fabric/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPsGetter has a method to return a IPInterface.
// A group's client should implement this interface.
type IPsGetter interface {
	IPs() IPInterface
}

// IPInterface has methods to work with IP resources.
type IPInterface interface {
	Create(ctx context.Context, iP *fabricv1.IP, opts metav1.CreateOptions) (*fabricv1.IP, error)
	Update(ctx context.Context, iP *fabricv1.IP, opts metav1.UpdateOptions) (*fabricv1.IP, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*fabricv1.IP, error)
	List(ctx context.Context, opts metav1.ListOptions) (*fabricv1.IPList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *fabricv1.IP, err error)
	Apply(ctx context.Context, iP *applyconfigurationfabricv1.IPApplyConfiguration, opts metav1.ApplyOptions) (result *fabricv1.IP, err error)
	IPExpansion
}

// iPs implements IPInterface
type iPs struct {
	*gentype.ClientWithListAndApply[*fabricv1.IP, *fabricv1.IPList, *applyconfigurationfabricv1.IPApplyConfiguration]
}

// newIPs returns a IPs
func newIPs(c *FabricV1Client) *iPs {
	return &iPs{
		gentype.NewClientWithListAndApply[*fabricv1.IP, *fabricv1.IPList, *applyconfigurationfabricv1.IPApplyConfiguration](
			"ips",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *fabricv1.IP { return &fabricv1.IP{} },
			func() *fabricv1.IPList { return &fabricv1.IPList{} },
		),
	}
}
