/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	fabricv1 "github.com/cloudyfolks-labs/fabric/pkg/apis/fabric/v1"
	applyconfigurationfabricv1 "github.com/cloudyfolks-labs/fabric/pkg/client/applyconfiguration/fabric/v1"
	scheme "github.com/cloudyfolks-labs/fabric/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProviderNetworksGetter has a method to return a ProviderNetworkInterface.
// A group's client should implement this interface.
type ProviderNetworksGetter interface {
	ProviderNetworks() ProviderNetworkInterface
}

// ProviderNetworkInterface has methods to work with ProviderNetwork resources.
type ProviderNetworkInterface interface {
	Create(ctx context.Context, providerNetwork *fabricv1.ProviderNetwork, opts metav1.CreateOptions) (*fabricv1.ProviderNetwork, error)
	Update(ctx context.Context, providerNetwork *fabricv1.ProviderNetwork, opts metav1.UpdateOptions) (*fabricv1.ProviderNetwork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, providerNetwork *fabricv1.ProviderNetwork, opts metav1.UpdateOptions) (*fabricv1.ProviderNetwork, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*fabricv1.ProviderNetwork, error)
	List(ctx context.Context, opts metav1.ListOptions) (*fabricv1.ProviderNetworkList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *fabricv1.ProviderNetwork, err error)
	Apply(ctx context.Context, providerNetwork *applyconfigurationfabricv1.ProviderNetworkApplyConfiguration, opts metav1.ApplyOptions) (result *fabricv1.ProviderNetwork, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, providerNetwork *applyconfigurationfabricv1.ProviderNetworkApplyConfiguration, opts metav1.ApplyOptions) (result *fabricv1.ProviderNetwork, err error)
	ProviderNetworkExpansion
}

// providerNetworks implements ProviderNetworkInterface
type providerNetworks struct {
	*gentype.ClientWithListAndApply[*fabricv1.ProviderNetwork, *fabricv1.ProviderNetworkList, *applyconfigurationfabricv1.ProviderNetworkApplyConfiguration]
}

// newProviderNetworks returns a ProviderNetworks
func newProviderNetworks(c *FabricV1Client) *providerNetworks {
	return &providerNetworks{
		gentype.NewClientWithListAndApply[*fabricv1.ProviderNetwork, *fabricv1.ProviderNetworkList, *applyconfigurationfabricv1.ProviderNetworkApplyConfiguration](
			"provider-networks",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *fabricv1.ProviderNetwork { return &fabricv1.ProviderNetwork{} },
			func() *fabricv1.ProviderNetworkList { return &fabricv1.ProviderNetworkList{} },
		),
	}
}
