/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	fabricv1 "github.com/cloudyfolks-labs/fabric/pkg/apis/fabric/v1"
	applyconfigurationfabricv1 "github.com/cloudyfolks-labs/fabric/pkg/client/applyconfiguration/fabric/v1"
	scheme "github.com/cloudyfolks-labs/fabric/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VpcsGetter has a method to return a VpcInterface.
// A group's client should implement this interface.
type VpcsGetter interface {
	Vpcs() VpcInterface
}

// VpcInterface has methods to work with Vpc resources.
type VpcInterface interface {
	Create(ctx context.Context, vpc *fabricv1.Vpc, opts metav1.CreateOptions) (*fabricv1.Vpc, error)
	Update(ctx context.Context, vpc *fabricv1.Vpc, opts metav1.UpdateOptions) (*fabricv1.Vpc, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vpc *fabricv1.Vpc, opts metav1.UpdateOptions) (*fabricv1.Vpc, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*fabricv1.Vpc, error)
	List(ctx context.Context, opts metav1.ListOptions) (*fabricv1.VpcList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *fabricv1.Vpc, err error)
	Apply(ctx context.Context, vpc *applyconfigurationfabricv1.VpcApplyConfiguration, opts metav1.ApplyOptions) (result *fabricv1.Vpc, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, vpc *applyconfigurationfabricv1.VpcApplyConfiguration, opts metav1.ApplyOptions) (result *fabricv1.Vpc, err error)
	VpcExpansion
}

// vpcs implements VpcInterface
type vpcs struct {
	*gentype.ClientWithListAndApply[*fabricv1.Vpc, *fabricv1.VpcList, *applyconfigurationfabricv1.VpcApplyConfiguration]
}

// newVpcs returns a Vpcs
func newVpcs(c *FabricV1Client) *vpcs {
	return &vpcs{
		gentype.NewClientWithListAndApply[*fabricv1.Vpc, *fabricv1.VpcList, *applyconfigurationfabricv1.VpcApplyConfiguration](
			"vpcs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *fabricv1.Vpc { return &fabricv1.Vpc{} },
			func() *fabricv1.VpcList { return &fabricv1.VpcList{} },
		),
	}
}
