/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	fabricv1 "github.com/cloudyfolks-labs/fabric/pkg/apis/fabric/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OvnDnatRuleLister helps list OvnDnatRules.
// All objects returned here must be treated as read-only.
type OvnDnatRuleLister interface {
	// List lists all OvnDnatRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*fabricv1.OvnDnatRule, err error)
	// Get retrieves the OvnDnatRule from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*fabricv1.OvnDnatRule, error)
	OvnDnatRuleListerExpansion
}

// ovnDnatRuleLister implements the OvnDnatRuleLister interface.
type ovnDnatRuleLister struct {
	listers.ResourceIndexer[*fabricv1.OvnDnatRule]
}

// NewOvnDnatRuleLister returns a new OvnDnatRuleLister.
func NewOvnDnatRuleLister(indexer cache.Indexer) OvnDnatRuleLister {
	return &ovnDnatRuleLister{listers.New[*fabricv1.OvnDnatRule](indexer, fabricv1.Resource("ovndnatrule"))}
}
