/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	fabricv1 "github.com/cloudyfolks-labs/fabric/pkg/apis/fabric/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RouterLBRuleLister helps list RouterLBRules.
// All objects returned here must be treated as read-only.
type RouterLBRuleLister interface {
	// List lists all RouterLBRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*fabricv1.RouterLBRule, err error)
	// Get retrieves the RouterLBRule from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*fabricv1.RouterLBRule, error)
	RouterLBRuleListerExpansion
}

// routerLBRuleLister implements the RouterLBRuleLister interface.
type routerLBRuleLister struct {
	listers.ResourceIndexer[*fabricv1.RouterLBRule]
}

// NewRouterLBRuleLister returns a new RouterLBRuleLister.
func NewRouterLBRuleLister(indexer cache.Indexer) RouterLBRuleLister {
	return &routerLBRuleLister{listers.New[*fabricv1.RouterLBRule](indexer, fabricv1.Resource("routerlbrule"))}
}
