/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	fabricv1 "github.com/cloudyfolks-labs/fabric/pkg/apis/fabric/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SwitchLBRuleLister helps list SwitchLBRules.
// All objects returned here must be treated as read-only.
type SwitchLBRuleLister interface {
	// List lists all SwitchLBRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*fabricv1.SwitchLBRule, err error)
	// Get retrieves the SwitchLBRule from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*fabricv1.SwitchLBRule, error)
	SwitchLBRuleListerExpansion
}

// switchLBRuleLister implements the SwitchLBRuleLister interface.
type switchLBRuleLister struct {
	listers.ResourceIndexer[*fabricv1.SwitchLBRule]
}

// NewSwitchLBRuleLister returns a new SwitchLBRuleLister.
func NewSwitchLBRuleLister(indexer cache.Indexer) SwitchLBRuleLister {
	return &switchLBRuleLister{listers.New[*fabricv1.SwitchLBRule](indexer, fabricv1.Resource("switchlbrule"))}
}
