---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fabric-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fabric-webhook
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fabric-webhook
              topologyKey: kubernetes.io/hostname
      priorityClassName: system-cluster-critical
      serviceAccountName: ovn
      automountServiceAccountToken: true
      hostNetwork: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fabric-webhook
          image: "docker.io/cloudyfolks-labs/fabric:v1.16.0"
          imagePullPolicy: IfNotPresent
          command:
            - /fabric/fabric-webhook
          args:
            - --port=8443
            - --health-probe-port=8080
            - --v=3
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          - containerPort: 8080
            name: health-probe
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: fabric-webhook-secret
      nodeSelector:
        kubernetes.io/os: "linux"

---
kind: Service
apiVersion: v1
metadata:
  name: fabric-webhook
  namespace: kube-system
spec:
  ports:
    - name: fabric-webhook
      protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP
  selector:
    app: fabric-webhook
  sessionAffinity: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: fabric-webhook
  annotations:
    cert-manager.io/inject-ca-from: kube-system/fabric-webhook-serving-cert
webhooks:
- name: pod-ip-validating.fabric.io
  rules:
    - operations:
        - CREATE
      apiGroups:
        - "apps"
      apiVersions:
        - v1
      resources:
        - deployments
        - statefulsets
        - daemonsets
    - operations:
        - CREATE
      apiGroups:
        - "batch"
      apiVersions:
        - v1
      resources:
        - jobs
        - cronjobs
    - operations:
        - CREATE
      apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
    - operations:
        - CREATE
        - UPDATE
        - DELETE
      apiGroups:
        - "fabric.cloudyfolks.io"
      apiVersions:
        - v1
      resources:
        - subnets
        - vpcs
        - vips
        - loadbalancer-pools
  objectSelector:
    matchExpressions:
      - key: app
        operator: NotIn
        values:
          - fabric-webhook
  failurePolicy: Ignore
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
  clientConfig:
    service:
      namespace: kube-system
      name: fabric-webhook
      path: /validating
      port: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fabric-webhook-serving-cert
  namespace: kube-system
spec:
  dnsNames:
    - fabric-webhook.kube-system
    - fabric-webhook.kube-system.svc
    - fabric-webhook.kube-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: fabric-webhook-selfsigned-issuer
    group: cert-manager.io
  secretName: fabric-webhook-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: fabric-webhook-selfsigned-issuer
  namespace: kube-system
spec:
  selfSigned: {}
