/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DNSZoneSpecApplyConfiguration represents a declarative configuration of the DNSZoneSpec type for use
// with apply.
type DNSZoneSpecApplyConfiguration struct {
	Vpc     *string                           `json:"vpc,omitempty"`
	Records []DNSZoneRecordApplyConfiguration `json:"records,omitempty"`
}

// DNSZoneSpecApplyConfiguration constructs a declarative configuration of the DNSZoneSpec type for use with
// apply.
func DNSZoneSpec() *DNSZoneSpecApplyConfiguration {
	return &DNSZoneSpecApplyConfiguration{}
}

// WithVpc sets the Vpc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vpc field is set to the value of the last call.
func (b *DNSZoneSpecApplyConfiguration) WithVpc(value string) *DNSZoneSpecApplyConfiguration {
	b.Vpc = &value
	return b
}

// WithRecords adds the given value to the Records field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Records field.
func (b *DNSZoneSpecApplyConfiguration) WithRecords(values ...*DNSZoneRecordApplyConfiguration) *DNSZoneSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRecords")
		}
		b.Records = append(b.Records, *values[i])
	}
	return b
}
