/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// LoadBalancerPoolSpecApplyConfiguration represents a declarative configuration of the LoadBalancerPoolSpec type for use
// with apply.
type LoadBalancerPoolSpecApplyConfiguration struct {
	Subnet          *string                                 `json:"subnet,omitempty"`
	Announce        *string                                 `json:"announce,omitempty"`
	ServiceSelector *metav1.LabelSelectorApplyConfiguration `json:"serviceSelector,omitempty"`
	Default         *bool                                   `json:"default,omitempty"`
}

// LoadBalancerPoolSpecApplyConfiguration constructs a declarative configuration of the LoadBalancerPoolSpec type for use with
// apply.
func LoadBalancerPoolSpec() *LoadBalancerPoolSpecApplyConfiguration {
	return &LoadBalancerPoolSpecApplyConfiguration{}
}

// WithSubnet sets the Subnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subnet field is set to the value of the last call.
func (b *LoadBalancerPoolSpecApplyConfiguration) WithSubnet(value string) *LoadBalancerPoolSpecApplyConfiguration {
	b.Subnet = &value
	return b
}

// WithAnnounce sets the Announce field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Announce field is set to the value of the last call.
func (b *LoadBalancerPoolSpecApplyConfiguration) WithAnnounce(value string) *LoadBalancerPoolSpecApplyConfiguration {
	b.Announce = &value
	return b
}

// WithServiceSelector sets the ServiceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceSelector field is set to the value of the last call.
func (b *LoadBalancerPoolSpecApplyConfiguration) WithServiceSelector(value *metav1.LabelSelectorApplyConfiguration) *LoadBalancerPoolSpecApplyConfiguration {
	b.ServiceSelector = value
	return b
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *LoadBalancerPoolSpecApplyConfiguration) WithDefault(value bool) *LoadBalancerPoolSpecApplyConfiguration {
	b.Default = &value
	return b
}
